version: "3.8"

services:
  postgres:
    image: postgres:13.1
    container_name: free-code-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: free-code-nest
    volumes:
      - nestjs_free_code_db:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: free-code-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  nestjs_free_code_db:
